CREATE TABLE ticker (
                        security_instrument_id  BIGINT        NOT NULL REFERENCES security_instrument(id),
                        type_sector             INTEGER,
                        nin                     VARCHAR(50),
                        nin2                    VARCHAR(50),
                        ofic_list               BOOLEAN,
                        non_list                BOOLEAN,
                        cur_open_trades         DATE,                                   -- совпадает с curOpenTrades
                        amount                  NUMERIC(18,6),
                        instr_name_ru           VARCHAR(255),
                        instr_name_en           VARCHAR(255),
                        instr_name_kz           VARCHAR(255),
                        nind                    VARCHAR(50),
                        nind2                   VARCHAR(50),
                        exc_date                DATE,
                        spot                    BOOLEAN,
                        swop                    BOOLEAN,
                        underlying_ru           VARCHAR(255),
                        underlying_en           VARCHAR(255),
                        underlying_kz           VARCHAR(255),
                        settlement_schemes      TEXT,
                        typesec_ru              VARCHAR(255),
                        typesec_en              VARCHAR(255),
                        typesec_kz              VARCHAR(255),
                        category_offlist_ru     VARCHAR(255),
                        category_offlist_en     VARCHAR(255),
                        category_offlist_kz     VARCHAR(255),
                        securities_list_ru      VARCHAR(255),
                        securities_list_en      VARCHAR(255),
                        securities_list_kz      VARCHAR(255),
                        currency                VARCHAR(20),
                        trading_currency        VARCHAR(20),
                        settlement_currency     VARCHAR(20),
                        finish_date             DATE,
                        cupon                   NUMERIC(18,6),
                        cupon2                  NUMERIC(18,6),
                        fin_sec_ru              VARCHAR(255),
                        fin_sec_en              VARCHAR(255),
                        fin_sec_kz              VARCHAR(255),
                        offer_predmet           VARCHAR(255),
                        include_date_trade_list DATE,
                        bond_type_ru            VARCHAR(255),
                        bond_type_kz            VARCHAR(255),
                        bond_type_en            VARCHAR(255),
                        open_trade_date         DATE,                                   -- устаревшее, не используется в сущности
                        nbrk_view_ru            VARCHAR(255),
                        nbrk_view_en            VARCHAR(255),
                        nbrk_view_kz            VARCHAR(255),
                        gsec_type_ru            VARCHAR(255),
                        gsec_type_en            VARCHAR(255),
                        gsec_type_kz            VARCHAR(255),
                        is_index_kase           BOOLEAN,
                        is_kase_b               BOOLEAN,
                        susp_trddat             DATE,                                   -- соответствует suspTrdDat
                        resum_trddat            DATE,                                   -- соответствует resumTrdDat
                        incl_date               DATE,
                        excl_date               DATE,
                        basis                   VARCHAR(100),
                        ticker_category         VARCHAR(100),
                        PRIMARY KEY (security_instrument_id, type_sector, nin)
);
