spring:
  application:
    name: kase-stock-exchange-parser
  r2dbc:
    password: "0000"
    url: r2dbc:postgresql://localhost:5432/kase_db
    username: "postgres"
  liquibase:
    change-log: classpath:/db/changelog/master-changelog.yml
    enabled: true
    user: "postgres"
    password: "0000"
    url: jdbc:postgresql://localhost:5432/kase_db
server:
  port: 0

#logging:
#  level:
#    org:
#      springframework:
#        r2dbc: DEBUG