package kz.nurgissa.kasestockexchangeparser.service.report;

import kz.nurgissa.kasestockexchangeparser.model.dtos.ArbitrageItemDto;
import kz.nurgissa.kasestockexchangeparser.model.dtos.ReportMarketSnapshotDto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

public class ReportTestFixtures {

    public static ReportMarketSnapshotDto createTestSnapshot() {
        return ReportMarketSnapshotDto.builder()
                .generatedAt(LocalDateTime.now())
                .investmentAmount(new BigDecimal("26500000"))
                .macro(ReportMarketSnapshotDto.MacroReportStatsDto.builder()
                        .totalEquitiesTurnoverKzt(new BigDecimal("2134567890123"))
                        .totalEquitiesDeals(8420150L)
                        .top3ConcentrationPct(new BigDecimal("35.2"))
                        .fearAndGreedIndex(68)
                        .fearAndGreedLabel("GREED (Жадность)")
                        .baseRate(new BigDecimal("16.25"))
                        .inflationRate(new BigDecimal("8.6"))
                        .build())
                .battle(ReportMarketSnapshotDto.AssetBattleComparisonDto.builder()
                        .capitalAmount(new BigDecimal("26500000"))
                        .depositRate(new BigDecimal("14.5"))
                        .depositAnnualIncome(new BigDecimal("3842500"))
                        .depositNotes("КФГД 20 млн ₸")
                        .realEstatePrice(new BigDecimal("26500000"))
                        .monthlyRent(new BigDecimal("230000"))
                        .realEstateNetYield(new BigDecimal("8.1"))
                        .realEstateNetAnnualIncome(new BigDecimal("2150000"))
                        .realEstateNotes("Krisha.kz 1-комн")
                        .bondYield(new BigDecimal("17.45"))
                        .bondAnnualIncome(new BigDecimal("4624250"))
                        .bondAdvantageOverDeposit(new BigDecimal("781750"))
                        .bondAdvantageOverRealEstateMultiple(new BigDecimal("2.15"))
                        .bondNotes("0% ИПН")
                        .build())
                .topStocks(List.of(
                        ReportMarketSnapshotDto.StockReportItemDto.builder()
                                .code("KSPI")
                                .name("Kaspi.kz")
                                .sector("Финтех")
                                .exchange("KASE")
                                .currentPrice(new BigDecimal("55000"))
                                .currency("KZT")
                                .dayChangePct(new BigDecimal("1.85"))
                                .cumulativeVolumeKzt(new BigDecimal("750000000000"))
                                .cumulativeDeals(3200000L)
                                .monthlyVolumeKzt(new BigDecimal("65000000000"))
                                .monthlyDeals(250000L)
                                .avgDealSizeKzt(new BigDecimal("260000"))
                                .freeFloatPct(new BigDecimal("27.4"))
                                .isIpoSpo(false)
                                .participantType("INSTITUTIONAL_HEAVY")
                                .rsi14(62.4)
                                .sma20(53500.0)
                                .trend("BULLISH")
                                .build(),
                        ReportMarketSnapshotDto.StockReportItemDto.builder()
                                .code("HSBK")
                                .name("Halyk Bank")
                                .sector("Банки")
                                .exchange("KASE")
                                .currentPrice(new BigDecimal("380.5"))
                                .currency("KZT")
                                .dayChangePct(new BigDecimal("-0.45"))
                                .cumulativeVolumeKzt(new BigDecimal("420000000000"))
                                .cumulativeDeals(1800000L)
                                .monthlyVolumeKzt(new BigDecimal("35000000000"))
                                .monthlyDeals(140000L)
                                .avgDealSizeKzt(new BigDecimal("250000"))
                                .freeFloatPct(new BigDecimal("31.2"))
                                .isIpoSpo(false)
                                .participantType("RETAIL_DOMINATED")
                                .rsi14(51.8)
                                .sma20(382.0)
                                .trend("NEUTRAL")
                                .build()
                ))
                .allStocks(List.of(
                        ReportMarketSnapshotDto.StockReportItemDto.builder()
                                .code("KSPI")
                                .name("Kaspi.kz")
                                .sector("Финтех")
                                .exchange("KASE")
                                .currentPrice(new BigDecimal("55000"))
                                .currency("KZT")
                                .dayChangePct(new BigDecimal("1.85"))
                                .cumulativeVolumeKzt(new BigDecimal("750000000000"))
                                .cumulativeDeals(3200000L)
                                .monthlyVolumeKzt(new BigDecimal("65000000000"))
                                .monthlyDeals(250000L)
                                .avgDealSizeKzt(new BigDecimal("260000"))
                                .freeFloatPct(new BigDecimal("27.4"))
                                .isIpoSpo(false)
                                .participantType("INSTITUTIONAL_HEAVY")
                                .rsi14(62.4)
                                .sma20(53500.0)
                                .trend("BULLISH")
                                .build()
                ))
                .topQuasigovBonds(List.of(
                        ReportMarketSnapshotDto.BondReportItemDto.builder()
                                .code("JSBNb13")
                                .name("Отбасы Банк")
                                .category("QUASIGOV")
                                .currency("KZT")
                                .ytm(new BigDecimal("17.45"))
                                .coupon(new BigDecimal("16.80"))
                                .couponFrequency("Полугодовой")
                                .finishDate(LocalDate.now().plusYears(3))
                                .durationFormatted("3 г.")
                                .nominal(new BigDecimal("1000"))
                                .currentPrice(new BigDecimal("98.50"))
                                .discountPct(new BigDecimal("1.50"))
                                .isTaxExempt(true)
                                .build()
                ))
                .topDiscountBonds(List.of(
                        ReportMarketSnapshotDto.BondReportItemDto.builder()
                                .code("KZTKb3")
                                .name("Казахтелеком")
                                .category("QUASIGOV")
                                .currency("KZT")
                                .ytm(new BigDecimal("18.20"))
                                .coupon(new BigDecimal("14.00"))
                                .couponFrequency("Квартальный")
                                .finishDate(LocalDate.now().plusYears(2))
                                .durationFormatted("2 г.")
                                .nominal(new BigDecimal("1000"))
                                .currentPrice(new BigDecimal("91.50"))
                                .discountPct(new BigDecimal("8.50"))
                                .isTaxExempt(true)
                                .build()
                ))
                .allBonds(List.of(
                        ReportMarketSnapshotDto.BondReportItemDto.builder()
                                .code("JSBNb13")
                                .name("Отбасы Банк")
                                .category("QUASIGOV")
                                .currency("KZT")
                                .ytm(new BigDecimal("17.45"))
                                .coupon(new BigDecimal("16.80"))
                                .couponFrequency("Полугодовой")
                                .finishDate(LocalDate.now().plusYears(3))
                                .durationFormatted("3 г.")
                                .nominal(new BigDecimal("1000"))
                                .currentPrice(new BigDecimal("98.50"))
                                .discountPct(new BigDecimal("1.50"))
                                .isTaxExempt(true)
                                .build()
                ))
                .arbitragePairs(List.of(
                        ArbitrageItemDto.builder()
                                .companyName("Kaspi.kz")
                                .kaseCode("KSPI")
                                .aixCode("KSPI.Y")
                                .kasePrice(new BigDecimal("55000"))
                                .aixPrice(new BigDecimal("54500"))
                                .currency("KZT")
                                .spreadAbs(new BigDecimal("500"))
                                .spreadPercent(new BigDecimal("0.92"))
                                .recommendation("BUY_AIX")
                                .build()
                ))
                .paycheck12Months(List.of(
                        ReportMarketSnapshotDto.CouponMonthDto.builder()
                                .monthNumber(1)
                                .monthName("Янв 2027")
                                .issuerCode("JSBNb13")
                                .issuerName("Отбасы Банк")
                                .payoutAmount(new BigDecimal("385000"))
                                .build()
                ))
                .benchmarks(Map.of("BASE_RATE", new BigDecimal("16.25")))
                .build();
    }
}
