package kz.nurgissa.kasestockexchangeparser.model.mapper;

import kz.nurgissa.kasestockexchangeparser.model.dtos.SecurityInstrumentResponse;
import kz.nurgissa.kasestockexchangeparser.model.entities.*;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.stream.Collectors;

@Component
public class SecurityInstrumentMapper {

    public SecurityInstrumentEntity toSecurityInstrumentEntity(SecurityInstrumentResponse dto) {
        return SecurityInstrumentEntity.builder()
                .id(dto.getId())
                .code(dto.getCode())
                .secType(dto.getSecType())
                .price(dto.getPrice())
                .closePrice(dto.getClosePrice())
                .bestBid(dto.getBestBid())
                .bestOffer(dto.getBestOffer())
                .volkzt(dto.getVolkzt())
                .volusd(dto.getVolusd())
                .capit(dto.getCapit())
                .date0(dto.getDate0())
                .trand(dto.getTrand())
                .trandPercent(dto.getTrandPercent())
                .orgCode(dto.getOrgCode())
                .orgNameRu(dto.getOrgNameRu())
                .orgNameEn(dto.getOrgNameEn())
                .orgNameKz(dto.getOrgNameKz())
                .orgShortNameRu(dto.getOrgShortNameRu())
                .orgShortNameEn(dto.getOrgShortNameEn())
                .orgShortNameKz(dto.getOrgShortNameKz())
                .dealcnt(dto.getDealcnt())
                .finSecRu(dto.getFinSecRu())
                .finSecEn(dto.getFinSecEn())
                .finSecKz(dto.getFinSecKz())
                .boardRu(dto.getBoardRu())
                .boardEn(dto.getBoardEn())
                .boardKz(dto.getBoardKz())
                .repaymentStartDate(dto.getRepaymentStartDate())
                .dohod(dto.getDohod())
                .dohodTotal(dto.getDohodTotal())
                .monthlySparkLine(dto.getMonthlySparkLine())
                .monthTrand(dto.getMonthTrand())
                .monthTrandPercent(dto.getMonthTrandPercent())
                .cntMm(dto.getCntMm())
                .currencyType(dto.getCurrencyType())
                .volumeNumber(dto.getVolumeNumber())
                .volumeReleaseNumber(dto.getVolumeReleaseNumber())
                .volume(dto.getVolume())
                .volumeRelease(dto.getVolumeRelease())
                .mainMarketRu(dto.getMainMarketRu())
                .mainMarketEn(dto.getMainMarketEn())
                .mainMarketKz(dto.getMainMarketKz())
                .dtm(dto.getDtm())
                .ytm(dto.getYtm())
                .subcategoryNameRu(dto.getSubcategoryNameRu())
                .subcategoryNameEn(dto.getSubcategoryNameEn())
                .subcategoryNameKz(dto.getSubcategoryNameKz())
                .subcategoryShortnameRu(dto.getSubcategoryShortnameRu())
                .subcategoryShortnameEn(dto.getSubcategoryShortnameEn())
                .subcategoryShortnameKz(dto.getSubcategoryShortnameKz())
                .scheme(dto.getScheme())
                .tPlus(dto.getTPlus())
                .liquidClass(dto.getLiquidClass())
                .build();
    }

    public TickerEntity toTickerEntity(SecurityInstrumentResponse dto) {
        var t = dto.getTicker();
        if (t == null) return null;
        return TickerEntity.builder()
                .securityInstrumentId(dto.getId())
                .typeSector(t.getTypeSector())
                .nin(t.getNin())
                .nin2(t.getNin2())
                .oficList(t.getOficList())
                .nonList(t.getNonList())
                .curOpenTrades(t.getCurOpenTrades())
                .amount(t.getAmount())
                .instrNameRu(t.getInstrNameRu())
                .instrNameEn(t.getInstrNameEn())
                .instrNameKz(t.getInstrNameKz())
                .nind(t.getNind())
                .nind2(t.getNind2())
                .excDate(t.getExcDate())
                .spot(t.getSpot())
                .swop(t.getSwop())
                .underlyingRu(t.getUnderlyingRu())
                .underlyingEn(t.getUnderlyingEn())
                .underlyingKz(t.getUnderlyingKz())
                .settlementSchemes(t.getSettlementSchemes())
                .typesecRu(t.getTypesecRu())
                .typesecEn(t.getTypesecEn())
                .typesecKz(t.getTypesecKz())
                .categoryOfflistRu(t.getCategoryOfflistRu())
                .categoryOfflistEn(t.getCategoryOfflistEn())
                .categoryOfflistKz(t.getCategoryOfflistKz())
                .securitiesListRu(t.getSecuritiesListRu())
                .securitiesListEn(t.getSecuritiesListEn())
                .securitiesListKz(t.getSecuritiesListKz())
                .currency(t.getCurrency())
                .tradingCurrency(t.getTradingCurrency())
                .settlementCurrency(t.getSettlementCurrency())
                .finishDate(t.getFinishDate())
                .cupon(t.getCupon())
                .cupon2(t.getCupon2())
                .finSecRu(t.getFinSecRu())
                .finSecEn(t.getFinSecEn())
                .finSecKz(t.getFinSecKz())
                .offerPredmet(t.getOfferPredmet())
                .includeDateTradeList(t.getIncludeDateTradeList())
                .bondTypeRu(t.getBondTypeRu())
                .bondTypeKz(t.getBondTypeKz())
                .bondTypeEn(t.getBondTypeEn())
//                .includeTradeDate(t.getIncludeTradeDate())
                .nbrkViewRu(t.getNbrkViewRu())
                .nbrkViewEn(t.getNbrkViewEn())
                .nbrkViewKz(t.getNbrkViewKz())
                .gsecTypeRu(t.getGsecTypeRu())
                .gsecTypeEn(t.getGsecTypeEn())
                .gsecTypeKz(t.getGsecTypeKz())
                .isIndexKase(t.getIsIndexKase())
                .isKaseB(t.getIsKaseB())
                .suspTrdDat(t.getSuspTrdDat())
                .resumTrdDat(t.getResumTrdDat())
                .inclDate(t.getInclDate())
                .exclDate(t.getExclDate())
                .basis(t.getBasis())
                .tickerCategory(t.getTickerCategory())
                .build();
    }

    public List<MarketMakerEntity> toMarketMakerEntityList(SecurityInstrumentResponse dto) {
        return dto.getMarketMakers() == null
                ? List.of()
                : dto.getMarketMakers().stream()
                .map(mm -> MarketMakerEntity.builder()
                        .orgCode(mm.getOrgCode())
                        .orgNameRu(mm.getOrgNameRu())
                        .orgNameEn(mm.getOrgNameEn())
                        .orgNameKz(mm.getOrgNameKz())
                        .orgShortNameRu(mm.getOrgShortNameRu())
                        .orgShortNameEn(mm.getOrgShortNameEn())
                        .orgShortNameKz(mm.getOrgShortNameKz())
                        .orgShortestNameRu(mm.getOrgShortestNameRu())
                        .orgShortestNameEn(mm.getOrgShortestNameEn())
                        .orgShortestNameKz(mm.getOrgShortestNameKz())
                        .build())
                .collect(Collectors.toList());
    }
}
